import type { Topic } from "@/lib/types";

export const topic: Topic = {
  slug: "lld-ops",
  kind: "lld",
  title: "Notifications, jobs, and failure",
  short: "Send the note another way if the first way fails. Remember the work you could not finish.",
  bigIdea:
    "Operational toys are about what happens when a step fails. A notifier tries the next channel. A logger fans a line out to several appenders. A scheduler picks the most important due job. A queue retries, then gives up into a dead letter pile. A circuit breaker stops calling a thing that is clearly down. A workflow waits for the steps it depends on and can try a failed step again.",
  sections: [
    {
      id: "notification",
      name: "Notification Service",
      simple: "A note that tries the mailbox, then the phone, then a tap on the shoulder",
      example: "notification",
      body: [
        "A notifier holds named channels. send walks the names you pass, tries each, and returns on the first success with the list of attempts. If every name throws, the status is failed and the attempts explain why.",
        "Channels are functions you inject. Email, SMS, and push are three functions, not three copies of send. The demo fails email, fails SMS once, then succeeds on the second SMS try because the caller listed SMS twice.",
        "Listing a channel twice is a simple retry. A fancier retry would loop inside one channel with a delay. Both are valid. The attempts list is what makes the choice visible.",
      ],
      useWhen: ["A message must leave the program through a swappable channel."],
      skipWhen: ["One println is enough. Do not build a notifier for a log line."],
      questions: [
        "What do you return? Sent or failed, which channel worked, and every attempt.",
        "Pitfall: throwing away the first error when the fallback also fails, so nobody knows email was down.",
      ],
      remember: "Walk the channel list. Keep every attempt. Stop on the first success.",
    },
    {
      id: "notification-channels",
      name: "Notification Email/SMS/Push",
      simple: "Three doors out of the house. The note only needs one of them to open",
      body: [
        "The channel name is data. Adding a pager is a new function in the map, not a new switch in send. That is the open-closed idea applied to a toy.",
        "Each channel returns an id or throws. The notifier does not parse email protocols. If they ask, say the channel object would hide the provider.",
        "The order of names is the product choice: email then SMS then push, or whichever the user preferred. The class does not hard-code the order.",
      ],
      useWhen: ["They name more than one delivery medium."],
      skipWhen: ["One medium. A single function is the channel. Mention the map as the extension."],
      questions: [
        "Where is the preference order? In the list the caller passes, so a user setting can change it without a code change in send.",
        "Pitfall: a channel that returns null for failure instead of throwing, and a notifier that treats null as success.",
      ],
      remember: "Channels are interchangeable functions. The list decides the order.",
    },
    {
      id: "notification-retry",
      name: "Notification Retry and Fallback",
      simple: "Knock twice on the same door, then try the next door",
      body: [
        "Retry is 'same channel again'. Fallback is 'next channel'. The demo uses the list for both: email once, SMS twice, then it would have tried push.",
        "A delay belongs in the retry helper from the next sections, not inside every channel. Pass a sleep you can skip in tests.",
        "Fallback should not run after a success. The return sits inside the loop, immediately after a channel returns.",
      ],
      useWhen: ["They ask what you do when email is down."],
      skipWhen: ["Delivery is best-effort and loss is acceptable. One try is honest. Say you would add fallback if mail is the product."],
      questions: [
        "How do you tell retry from fallback in the attempts? The name repeats for a retry. A new name is a fallback.",
        "Pitfall: falling back after a successful send because you checked the wrong flag.",
      ],
      remember: "Retry repeats a name. Fallback moves to the next name. Success returns immediately.",
    },
    {
      id: "logging",
      name: "Logging Framework",
      simple: "A sentence with a loudness. Quiet sentences stay in the notebook. Loud ones also ring a bell",
      example: "logging",
      body: [
        "A logger has a minimum level and a list of appenders. log drops anything quieter than the minimum, then hands the row to every appender. Levels are debug, info, warn, and error, with ranks 10, 20, 30, and 40.",
        "The demo's floor is info, so debug is hidden. One appender stores the line. A second appender adds an alert when the level is error. The memory list is info, error, alert.",
        "The logger does not open files. An appender would. That split is the whole exercise.",
      ],
      useWhen: ["They want levels and more than one destination."],
      skipWhen: ["A single list of strings is the trace they asked for. You can still filter by level with one if."],
      questions: [
        "Who filters, the logger or the appender? The logger, so a debug line does not wake a slow appender. An appender may filter further.",
        "Pitfall: string compare on 'warn' and 'error', which is alphabetical and wrong.",
      ],
      remember: "Rank the level. Drop quieter lines. Then tell every appender.",
    },
    {
      id: "logging-appenders",
      name: "Logging Multiple Appenders and Levels",
      simple: "One sentence can land in the diary and on the grown-up's desk",
      body: [
        "Appenders are a list you pass in. The second one in the demo is a filter with a side write: only errors become alerts. That is a decorator-shaped appender.",
        "Changing the logger's floor changes every appender. If one destination wants debug and another wants error, the extra filter lives on the appender, and the logger floor is the quieter of the two.",
        "Do not log by concatenating into a global string. A row object can grow a timestamp later without breaking the appenders.",
      ],
      useWhen: ["They say console and file, or info and error, in the same breath."],
      skipWhen: ["One destination. A list of one is fine, and you do not need a framework hierarchy."],
      questions: [
        "What is an appender? A function from a log row to a side effect.",
        "Pitfall: one appender throwing and skipping the rest. Catch inside the loop if delivery to the others matters.",
      ],
      remember: "The floor is on the logger. Extra taste is on the appender.",
    },
    {
      id: "task-scheduler",
      name: "Task Scheduler",
      simple: "Slips of work. When the bell rings, do the ones whose time has come, important ones first",
      example: "task-scheduler",
      body: [
        "A job has a name, a runAt time, a priority, and an optional period. tick(now) selects jobs with runAt at or before now, sorts by priority descending, runs them, and either removes them or sets runAt to now plus the period.",
        "The demo's order at time 5 is high, then daily, then low. daily's period is 10, so it is not due at 14 and is due at 15.",
        "Running inline is the interview model. A worker pool would pull from this same due list. Say the tick is the decision, not the threads.",
      ],
      useWhen: ["Work should happen at a time, maybe again later."],
      skipWhen: ["They want a distributed cron. The job and the due rule are the same. The lease that stops two servers running it is the follow-up."],
      questions: [
        "What is priority versus runAt? runAt decides eligibility. Priority orders the ones that are eligible together.",
        "Pitfall: setting the next runAt from the old runAt plus period, and drifting if tick is late. This model schedules from now.",
      ],
      remember: "Due if runAt <= now. Higher priority first. A period moves runAt forward.",
    },
    {
      id: "scheduler-priorities",
      name: "Task Scheduler Priorities and Recurring Jobs",
      simple: "The red slip goes before the blue slip, and the blue slip comes back tomorrow",
      body: [
        "A one-shot job is removed after it runs. A recurring job stays, with a new runAt. Mixing those in one class is fine because the difference is a single number, the period, zero meaning once.",
        "If two jobs share a priority, the earlier runAt wins, which the sort's second key does. Say it so ties are not accidental.",
        "A job that throws is not in this demo. The job queue lesson is where retry lives. You can point at it instead of growing the scheduler into a queue.",
      ],
      useWhen: ["They add 'daily' or 'the urgent one first' after the basic tick."],
      skipWhen: ["Every job is equal and runs once. Priority can default to zero."],
      questions: [
        "Does recurring mean from the scheduled time or from the actual run? Here, from the tick's now, so a late tick does not schedule a stampede of catch-up runs.",
        "Pitfall: removing a recurring job because you treated every run as one-shot.",
      ],
      remember: "Period zero means delete after run. Any other period means schedule again.",
    },
    {
      id: "job-queue",
      name: "Job Queue",
      simple: "A pile of chores. If a chore fails, it goes back. If it fails too often, it goes in the bad pile",
      figure: "job-slips",
      example: "job-queue",
      body: [
        "push adds a job and sorts by priority. work takes the front. Success returns done. A throw increments attempts and, if attempts are still under the max, puts the job back and returns retry. At the max, the job moves to the dead list.",
        "The demo's max is 2. The hot job fails once, succeeds the second time, and only then does the slow job run. A later bad job dies on the second failure.",
        "This queue is in memory and runs on the caller of work. A real worker would loop. The states are what the interview grades.",
      ],
      useWhen: ["Tasks can fail and should be tried again, with a place for the ones that never succeed."],
      skipWhen: ["Failure is impossible in the toy. A list you pop is enough."],
      questions: [
        "What is the dead letter queue? The list of jobs that used up their attempts. You can inspect it. You do not retry it automatically.",
        "Pitfall: incrementing attempts on success, or sorting only at push and forgetting to sort after a retry.",
      ],
      remember: "Priority order. Failures come back until the max, then they sit in the dead list.",
    },
    {
      id: "job-queue-retry",
      name: "Job Queue Retry/DLQ/Priorities",
      simple: "Important chores jump the line. Hopeless chores leave the line",
      body: [
        "Priority is reapplied after a retry so a hot job still beats a slow one. The dead list does not participate in that sort.",
        "DLQ means dead letter queue: the pile you keep so a human, or a later replay tool, can see the poison job. Dropping it on the floor makes the bug invisible.",
        "A delay before retry is the upgrade. Store notBefore on the job and skip it in work until the clock passes. The circuit and retry lessons show the wait math.",
      ],
      useWhen: ["They say retry, dead letter, or priority in one prompt."],
      skipWhen: ["They only want a FIFO list. Ship FIFO, then add the counter when they ask what a failure does."],
      questions: [
        "Does a retry go to the back or stay urgent? Here it is sorted again by priority, so it can stay at the front.",
        "Pitfall: a max of 2 meaning two retries plus the original, or two tries total. This code uses two tries total. Say the number.",
      ],
      remember: "Attempts count tries. The dead list is the visible failure. Priority is re-sorted.",
    },
    {
      id: "retry-mechanism",
      name: "Retry Mechanism",
      simple: "Try the trick again, but wait a little longer each time you miss",
      example: "retry",
      body: [
        "retry calls work with the attempt number, up to a max. On failure it asks delayFor for a wait, except after the last attempt, and then throws the last error.",
        "The demo succeeds on attempt 3 and records waits of 10 and 20, which is 10 * 2^(attempt-1) after the first two failures. No wait is recorded after the success, and none after the final failure because there is no next try.",
        "The helper does not know about HTTP. The work function decides what is a failure by throwing. A 400 that should not retry must not throw a retryable error.",
      ],
      useWhen: ["Several call sites need the same backoff, so you do not copy the loop."],
      skipWhen: ["One call site and no wait. A for loop is clearer than a framework."],
      questions: [
        "What is injected? The work and the delay, so the test does not sleep.",
        "Pitfall: retrying non-retryable errors because every throw looks the same.",
      ],
      remember: "A loop, a max, a delay function, and the last error if you give up.",
    },
    {
      id: "circuit-breaker",
      name: "Circuit Breaker",
      simple: "If the flashlight fails twice, stop clicking it until a little time has passed",
      example: "circuit-breaker",
      body: [
        "The breaker wraps a call. It counts failures while closed. At the limit it opens and remembers when. Calls during the cooldown throw without running the work. After the cooldown, one call is allowed through: half-open.",
        "A success in half-open closes the breaker and clears the count. A failure opens it again.",
        "The demo uses a limit of 2 and a cooldown of 10. Failures at time 0 and 1 open it. A call at time 5 is blocked. A success at time 11 closes it.",
      ],
      useWhen: ["A dependency is down and retrying it immediately will make things worse."],
      skipWhen: ["Failures are rare and cheap. A retry loop is enough. Mention the breaker as the thing you add when the dependency stays down."],
      questions: [
        "What does open protect? The caller, from waiting, and the dependency, from a herd of retries.",
        "Pitfall: counting a success toward the failure limit, or forgetting to reset the count on close.",
      ],
      remember: "Closed counts failures. Open refuses. Half-open lets one call decide.",
    },
    {
      id: "circuit-states",
      name: "Circuit Breaker Closed/Open/Half-Open",
      simple: "The switch is on, then off, then 'try once and see'",
      body: [
        "Closed is normal. Open is the fast fail. Half-open is the probe. Draw the three boxes before you code the ifs, because the bugs are illegal jumps: a success from open without a probe, or a probe that does not change state.",
        "The cooldown is compared with the injected now. openedAt plus cooldown is the first legal probe time. The demo's 5 is inside and 11 is outside a cooldown of 10 from time 1.",
        "Half-open should allow one in-flight call in a concurrent program. This model is single-threaded, so one call at a time is natural. Say the lock you would add.",
      ],
      useWhen: ["They ask you to name the states, not only the threshold."],
      skipWhen: ["A boolean 'down' is all they wanted. You can still mention half-open in a sentence."],
      questions: [
        "When do you leave open? When now reaches openedAt plus cooldown, and only into half-open, not straight to closed.",
        "Pitfall: two probes both passing the time check and both hitting the sick dependency.",
      ],
      remember: "Open does not heal by itself. A successful probe heals it.",
    },
    {
      id: "workflow",
      name: "Workflow Engine",
      simple: "Chores in a row, except some chores may not start until another chore is finished",
      example: "workflow",
      body: [
        "Each step has an id, a list of needs, a work function, and a status: pending, done, or failed. ready returns pending steps whose needs are all done. run executes one ready step and marks it done or failed.",
        "retry moves failed back to pending so the next run can try again. It does not skip the dependency check.",
        "The demo reserves, fails the first payment, refuses to ship, retries payment, then ships. Dependencies, not a hardcoded order, are what block ship.",
      ],
      useWhen: ["Steps have a partial order and a step can fail without failing the ones that already succeeded."],
      skipWhen: ["A straight line of calls. Write the calls. A workflow object for three lines is heavy, unless they asked for failure recovery."],
      questions: [
        "What makes a step ready? Pending, and every need is done. Failed needs do not count.",
        "Pitfall: running every pending step and noticing the dependency after the side effect.",
      ],
      remember: "Ready means dependencies are done. Failed can return to pending. It cannot skip ahead.",
    },
    {
      id: "workflow-recovery",
      name: "Workflow Engine Dependencies and Failure Recovery",
      simple: "If the payment chore falls over, the shipping chore waits. You may pick the payment chore up again",
      body: [
        "Recovery is retry on the failed id, not a restart of the whole flow. reserve stays done. That is why status lives on the step.",
        "A second failure would leave pay failed again. You could add an attempt cap and point at the dead letter idea. The demo stops at one recovery.",
        "Cycles in needs would make ready forever empty. If you build this for real, reject a graph that contains a cycle when you add the step.",
      ],
      useWhen: ["They ask how a failed middle step is repaired."],
      skipWhen: ["Any failure aborts everything. Mark the workflow failed and stop. Retry-from-here is the extra they did not ask for yet."],
      questions: [
        "What is preserved on retry? The steps already done. Only the failed step becomes pending.",
        "Pitfall: re-running reserve and holding the inventory twice.",
      ],
      remember: "Do not restart from the first step. Move the failed step back to pending.",
    },
  ],
  recap: [
    "Notifications try a list of channels and remember each attempt.",
    "Logs have levels and appenders. Schedulers have due times and priority. Queues have retries and a dead list.",
    "A breaker has three states. A workflow runs ready steps and retries a failed step without redoing the ones that succeeded.",
  ],
  words: [
    { term: "Appender", meaning: "A destination for a log row, such as memory, a console, or an alert." },
    { term: "Dead letter", meaning: "A job that used up its retries and is kept for inspection." },
    { term: "Half-open", meaning: "The breaker state that allows one trial call after a cooldown." },
  ],
};
