import type { Topic } from "@/lib/types";

export const topic: Topic = {
  slug: "operational-scale-cost",
  kind: "concept",
  title: "Operational Scale and Cost",
  short: "Spending money on computers wisely: seeing who spends what, planning for busy days, and saving the fancy treatment for what matters.",
  bigIdea:
    "Imagine you get a weekly allowance. If you spend it all on Monday, there is nothing left for the field trip on Friday. If you never look at where it goes, a little here and a little there quietly adds up. Big computer systems are the same, except the allowance can be millions of dollars a month. Every computer we rent, every file we store, and every message we send from one place to another costs money. Good teams watch the spending, plan ahead for the busy days, keep enough spare for emergencies, and save the expensive, extra careful treatment for the things that truly need it.",
  sections: [
    {
      id: "finops",
      name: "FinOps",
      simple: "The whole family plans the allowance together",
      body: [
        "Long ago, buying a computer server took weeks of paperwork, so spending was slow and easy to see. In the cloud, where you rent computers from a big company by the hour, any engineer can rent a hundred computers in a minute. That is wonderful for speed, but it also means money can leak away quickly and quietly.",
        "FinOps (short for financial operations) is the habit of engineers, finance people, and business leaders working on cloud spending together. It is like a family planning the allowance as a team. The kids know what they need, the parents know the budget, and everyone gets to see the receipts.",
        "The FinOps Foundation, a group that shares good practice, describes the work as a loop with three phases: Inform, Optimize, and Operate. You go around the loop again and again, because every new feature brings new costs.",
      ],
      figure: "loop-track",
      remember: "Cost is everyone's job, and it is a loop you keep repeating, not a one-time cleanup.",
    },
    {
      id: "inform",
      name: "Inform: cost visibility and unit economics",
      simple: "Put a name sticker on every toy so you know whose it is",
      body: [
        "You cannot save money if you do not know where it goes. So the first step is to label everything. Each rented computer, database, and storage space gets a tag, a little name sticker saying which team owns it and which product it is for. Things with no tag are like lost toys at the end of the school year: nobody knows who to ask about them.",
        "With tags in place, each team can see its own bill. Just showing a team its costs is called showback. Actually taking the money out of that team's budget is called chargeback. Showback is gentler and a good place to start. Chargeback makes people care more, but it needs very accurate tags, and shared things, like one database many teams use, must be split fairly, which can start arguments.",
        "Often the most useful number is not the total bill but the cost of one unit of work, such as the cost per order or the cost per active user each month. This is called unit economics. If the bill doubles because twice as many people are shopping, that is fine. If the cost of each order doubles, something is being wasted.",
      ],
      remember: "Tag everything, show every team its spending, and watch the cost of one unit of work.",
    },
    {
      id: "optimize",
      name: "Optimize: rightsizing, autoscaling and commitments",
      simple: "Do not rent a whole bus to carry two kids",
      body: [
        "Once we can see the spending, we hunt for waste, and the biggest wins are usually simple. Rightsizing means picking a smaller computer when the big one sits mostly idle, like trading a bus for a car when only two kids ride. Turning off idle things means shutting down test computers at night and deleting old copies that nobody uses.",
        "Autoscaling lets the system add computers when it gets busy and remove them when it gets quiet, like opening extra lunch lines only during the rush. It saves money in quiet hours. But new computers take a few minutes to start, so autoscaling alone cannot catch a sudden spike.",
        "We can also pay less for the very same computer by buying it differently. On-demand is full price: pay by the hour and stop anytime. A commitment, such as reserved instances or savings plans, means promising to use a certain amount for one or three years in exchange for a big discount, which suits steady load you are sure about. Spot (or preemptible) computers are spare ones the cloud sells cheaply, but it can take them back with only a short warning, so they suit jobs that can stop and start again, like resizing a big pile of photos.",
        "Old data can also slide to cheaper storage automatically, which we will see in the tiering part. The trade-offs: commitments lock you in if your needs shrink, spot computers can vanish mid-job, and squeezing too hard leaves no spare room for a busy day.",
      ],
      figure: "bus-or-car",
      remember: "First stop paying for what you do not use, then pay less for what you do use.",
    },
    {
      id: "operate",
      name: "Operate: budgets, alerts and habits",
      simple: "Check the piggy bank every week, not once a year",
      body: [
        "Savings fade if nobody keeps watching. In the Operate phase, teams set budgets, like a spending limit for each team each month, and alerts that warn when spending is heading past the limit before the month is over.",
        "Good teams also watch for surprises, called anomalies. If one service suddenly costs five times more on a Tuesday, someone hears about it that day, not when the bill arrives weeks later. Often it is a mistake, like a test left running all weekend or a bug sending far too many messages.",
        "Then come the habits: look at costs in regular team meetings, think about cost when designing new features, and clean up after experiments. The trade-off is time. Watching costs takes effort, so teams start with the biggest items, because a few services usually make up most of the bill.",
      ],
      remember: "Budgets, alerts, and regular check-ins stop savings from slowly leaking away.",
    },
    {
      id: "capacity-planning",
      name: "Capacity planning",
      simple: "Get enough chairs before the party, not during it",
      body: [
        "Capacity is how much work our computers can handle. Capacity planning is guessing how much we will need in the future and getting it ready in time. It is like planning a birthday party: how many friends are coming this year, how many will crowd in at the busiest moment when the cake comes out, and how many extra chairs to set out just in case.",
        "First, we forecast. We look at how fast use is growing and at the busy peaks, like holidays or a big sale, which can be several times a normal day. Then we add headroom, which is spare room on top of the expected peak. Headroom covers surprises, and it also matters because computers slow down when they are nearly full. Like a lunch line, the closer it gets to full, the faster the waiting grows.",
        "Second, we respect lead time, which is how long it takes to get more. Buying real servers for our own building can take months. Even in the cloud, very large amounts or special machines may need to be requested ahead of time. So we order before we run out, not when we run out.",
        "Third, we measure the real limit with a load test: we send pretend traffic to a server until it starts to struggle, so we know how much one server can truly handle. Planning for too much wastes money on idle computers. Planning for too little means slow pages, or an outage, on the busiest day of the year.",
      ],
      figure: "party-chairs",
      remember: "Forecast the peak, add headroom, and order early enough to cover the lead time.",
    },
    {
      id: "active-active",
      name: "Multi-region active-active",
      simple: "Several lemonade stands, each ready to serve a neighbor's customers",
      body: [
        "A region is a group of data centers in one part of the world, like one city's worth of computer buildings. In an active-active setup, every region serves real customers all the time. Think of three lemonade stands in three neighborhoods, all open. If one stand gets rained out, its customers walk to the other two.",
        "That only works if the other stands have room for them. Here is the key math. With N equal regions, if one fails, the other N minus 1 must carry everything. So on a normal day each region can be at most (N minus 1) out of N busy. With 2 regions that is 50 percent each. With 3 regions it is about 67 percent, and with 4 regions it is 75 percent. These are ceilings, and real teams stay a little below them so the survivors are not completely full after a failure.",
        "More regions waste less spare room, but they bring new costs. Data must be copied between regions, and cloud providers charge for data that travels from one region to another. Every extra region is more computers to run and watch.",
        "Keeping data correct is harder too. If a kid changes an order in one region while another region still holds the old copy, the two can disagree. Teams handle this by giving each customer a home region for changes, or by carefully merging changes later. And copying data across the world is limited by the speed of light, so waiting for every region to confirm each change makes things slower. Many teams accept a short delay instead.",
      ],
      figure: "lemonade-stands",
      remember: "With N regions, keep each one at most (N minus 1) out of N busy, so the others can catch a fallen one.",
    },
    {
      id: "tiering",
      name: "Resource tiering",
      simple: "Not every toy needs the special shelf",
      body: [
        "Giving everything the gold treatment is the fastest way to an enormous bill. Resource tiering means sorting things by how important they are, or how often they are used, and giving each group just the right level of care.",
        "Service tiers. The most critical services, often called tier 0 or tier 1, like checkout and payments and the things they depend on, get the most spare copies, the fastest alerts, and usually run in several regions. Lower tiers, like the box that suggests other toys you might like, are allowed to slow down or switch off for a while when things go wrong. If suggestions vanish for an hour, people can still buy things. If checkout breaks, nobody can.",
        "Storage tiers. Hot storage is like the fridge: right there and very fast, but the most expensive place to keep each item. Warm storage is the pantry: a few steps away and cheaper. Cold storage is the attic: cheaper still, but slower, and there is often a small fee each time you fetch something and a minimum time things must stay. Archive is a storage unit across town: the cheapest place to keep things, but getting something back can take hours and costs extra. Lifecycle rules move data down this ladder automatically as it gets older.",
        "Compute tiers. We met these earlier: commitments for the steady base, on-demand for bumps and new work, and spot for jobs that can be interrupted. The trade-off of all tiering is that the choices must be right. Put something in too low a tier and it may be slow or fragile just when it suddenly matters, like an archived file a customer needs today.",
      ],
      figure: "fridge-attic",
      remember: "Give each thing the care it needs: gold for the critical, cheap shelves for the rarely used.",
    },
  ],
  recap: [
    "Cloud spending can grow quietly, so engineers, finance, and business plan it together. That teamwork is FinOps.",
    "FinOps is a loop: Inform (tag everything, show who spends what), Optimize (remove waste, buy smarter), Operate (budgets, alerts, habits).",
    "Track the cost of one unit of work, like cost per order, not just the total bill.",
    "Capacity planning: forecast the peak, add headroom, and order ahead of the lead time. Load test to learn the real limits.",
    "Active-active with N regions: keep each region at most (N minus 1) out of N busy. Two regions means 50 percent, three means about 67 percent.",
    "More regions waste less spare room but add data copying costs and complexity.",
    "Tier things: critical services, hot data, and steady load get the careful treatment, and everything else gets something cheaper.",
  ],
  words: [
    { term: "FinOps", meaning: "Engineers, finance, and business people working together on cloud spending." },
    { term: "Tag", meaning: "A label on a cloud resource saying who owns it and what it is for." },
    { term: "Showback and chargeback", meaning: "Showing each team its costs, or actually billing the team for them." },
    { term: "Unit economics", meaning: "The cost of one unit of work, like one order or one active user." },
    { term: "Rightsizing", meaning: "Picking a computer size that matches the real work." },
    { term: "Commitment (reserved instances, savings plans)", meaning: "A discount for promising to use computers for one to three years." },
    { term: "Spot instance", meaning: "A cheap spare computer that the cloud can take back at short notice." },
    { term: "Headroom", meaning: "Spare capacity kept above the expected peak." },
    { term: "Lead time", meaning: "How long it takes to get more capacity after you ask for it." },
    { term: "Active-active", meaning: "Every region serves live traffic at the same time and covers for the others." },
  ],
};
