// Turns the Hairline figures in hairline/figures/*.js into modules the site can load.
//
// Each figure file is written in the hairline-create skill's format, so the skill's own
// build, validate and look scripts work on it unchanged: it reads `HL` from the kernel and
// ends with `hairline({ name, means, rules, range, tour, mount })`. Here every file is
// wrapped, without changing a character of it, into an ES module that imports the kernel
// and exports that definition. The kernel is wrapped the same way.
//
// It also writes meta.json (name, means, range and tour of every figure, read without a
// DOM) and registry.ts (one lazy loader per figure, so each figure is its own small chunk).
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import vm from "node:vm";

const root = new URL("..", import.meta.url).pathname;
const src = join(root, "hairline");
const out = join(root, "components/figures/generated");

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });

const kernel = readFileSync(join(src, "kernel.js"), "utf8");
writeFileSync(join(out, "kernel.js"), `${kernel}\nexport { HL };\n`);
writeFileSync(join(out, "kernel.d.ts"), "// eslint-disable-next-line @typescript-eslint/no-explicit-any\nexport declare const HL: any;\n");

// Reading a figure's definition needs no DOM: nothing runs until mount.
const stub = new Proxy({}, { get: () => () => undefined });

const files = readdirSync(join(src, "figures")).filter((f) => f.endsWith(".js")).sort();
const meta = {};
for (const file of files) {
  const code = readFileSync(join(src, "figures", file), "utf8");
  let def;
  vm.runInNewContext(code, { HL: stub, hairline: (d) => (def = d), Math, Number, Array, Object, Map, Set, String });
  if (!def?.name) throw new Error(`${file}: no hairline({ name }) call`);
  if (`${def.name}.js` !== file) throw new Error(`${file}: its name is "${def.name}"; the file must be named ${def.name}.js`);
  meta[def.name] = { means: def.means, range: def.range, tour: def.tour ?? null, rules: def.rules };

  writeFileSync(
    join(out, file),
    `import { HL } from "./kernel.js";\nlet __figure;\nconst hairline = (f) => { __figure = f; };\n${code}\nexport default __figure;\n`,
  );
  writeFileSync(join(out, file.replace(/\.js$/, ".d.ts")), 'import type { FigureDef } from "../types";\ndeclare const figure: FigureDef;\nexport default figure;\n');
}

writeFileSync(join(out, "meta.json"), JSON.stringify(meta, null, 2) + "\n");
const loaders = files
  .map((f) => `  ${JSON.stringify(f.slice(0, -3))}: () => import("./${f}"),`)
  .join("\n");
writeFileSync(
  join(out, "registry.ts"),
  `// Generated by scripts/figures.mjs. Do not edit.\nimport type { FigureDef } from "../types";\n\nexport const loaders: Record<string, () => Promise<{ default: FigureDef }>> = {\n${loaders}\n};\n`,
);
console.log(`figures: wrapped ${files.length} figure${files.length === 1 ? "" : "s"} and the kernel`);
